const bcrypt = require('bcryptjs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../../.env') });
const pool = require('./config/database');
const fs = require('fs');

const seedDatabase = async () => {
  try {
    console.log('Starting database seed...');

    // Read and execute schema
    const schemaPath = path.join(__dirname, 'models/schema.sql');
    const schema = fs.readFileSync(schemaPath, 'utf8');
    await pool.query(schema);
    console.log('Schema created successfully');

    // Create demo user
    const hashedPassword = await bcrypt.hash('admin123', 10);
    const userResult = await pool.query(`
      INSERT INTO users (email, password, name, role)
      VALUES ($1, $2, $3, $4)
      RETURNING id
    `, ['admin@reviewmanager.com', hashedPassword, 'Admin User', 'admin']);
    const userId = userResult.rows[0].id;
    console.log('Demo user created');

    // Seed Businesses (15+ items)
    const businesses = [
      { name: 'Bella Italia Restaurant', platform: 'google', address: '123 Main St, New York, NY', phone: '(212) 555-0101', category: 'Italian Restaurant', rating: 4.5 },
      { name: 'Tokyo Sushi Bar', platform: 'yelp', address: '456 Oak Ave, Los Angeles, CA', phone: '(310) 555-0102', category: 'Japanese Restaurant', rating: 4.7 },
      { name: 'Sunrise Cafe', platform: 'google', address: '789 Pine Rd, Chicago, IL', phone: '(312) 555-0103', category: 'Coffee Shop', rating: 4.2 },
      { name: 'Green Garden Bistro', platform: 'yelp', address: '321 Elm St, Houston, TX', phone: '(713) 555-0104', category: 'Vegetarian Restaurant', rating: 4.4 },
      { name: 'Downtown Deli', platform: 'google', address: '654 Market St, San Francisco, CA', phone: '(415) 555-0105', category: 'Deli', rating: 4.1 },
      { name: 'Coastal Seafood Grill', platform: 'yelp', address: '987 Beach Blvd, Miami, FL', phone: '(305) 555-0106', category: 'Seafood Restaurant', rating: 4.6 },
      { name: 'Mountain View Steakhouse', platform: 'google', address: '147 Highland Dr, Denver, CO', phone: '(303) 555-0107', category: 'Steakhouse', rating: 4.3 },
      { name: 'Sweet Treats Bakery', platform: 'yelp', address: '258 Sugar Lane, Boston, MA', phone: '(617) 555-0108', category: 'Bakery', rating: 4.8 },
      { name: 'Taco Fiesta', platform: 'google', address: '369 Spice Ave, Phoenix, AZ', phone: '(602) 555-0109', category: 'Mexican Restaurant', rating: 4.0 },
      { name: 'The Breakfast Club', platform: 'yelp', address: '741 Morning St, Seattle, WA', phone: '(206) 555-0110', category: 'Breakfast Restaurant', rating: 4.5 },
      { name: 'Pizza Paradise', platform: 'google', address: '852 Cheese Blvd, Philadelphia, PA', phone: '(215) 555-0111', category: 'Pizza Restaurant', rating: 4.2 },
      { name: 'Thai Orchid', platform: 'yelp', address: '963 Basil Way, Portland, OR', phone: '(503) 555-0112', category: 'Thai Restaurant', rating: 4.6 },
      { name: 'BBQ Pitmaster', platform: 'google', address: '159 Smokey Rd, Austin, TX', phone: '(512) 555-0113', category: 'BBQ Restaurant', rating: 4.7 },
      { name: 'French Quarter Bistro', platform: 'yelp', address: '267 Bourbon St, New Orleans, LA', phone: '(504) 555-0114', category: 'French Restaurant', rating: 4.4 },
      { name: 'Indian Spice House', platform: 'google', address: '378 Curry Lane, Atlanta, GA', phone: '(404) 555-0115', category: 'Indian Restaurant', rating: 4.3 }
    ];

    const businessIds = [];
    for (const biz of businesses) {
      const result = await pool.query(`
        INSERT INTO businesses (user_id, name, platform, address, phone, category, rating, review_count)
        VALUES ($1, $2, $3, $4, $5, $6, $7, 0)
        RETURNING id
      `, [userId, biz.name, biz.platform, biz.address, biz.phone, biz.category, biz.rating]);
      businessIds.push(result.rows[0].id);
    }
    console.log(`${businesses.length} businesses created`);

    // Seed Reviews (15+ items per platform, 30+ total)
    const reviews = [
      // Google Reviews
      { business_idx: 0, platform: 'google', reviewer_name: 'John D.', rating: 5, review_text: 'Absolutely amazing pasta! The carbonara was the best I\'ve ever had. Service was impeccable and the atmosphere was romantic and cozy.', sentiment: 'positive' },
      { business_idx: 0, platform: 'google', reviewer_name: 'Sarah M.', rating: 4, review_text: 'Great food, but the wait was a bit long. Would definitely come back though, the tiramisu was to die for!', sentiment: 'positive' },
      { business_idx: 0, platform: 'google', reviewer_name: 'Mike R.', rating: 2, review_text: 'Disappointed with my experience. The pizza was cold and the waiter was rude. Expected better for the price.', sentiment: 'negative' },
      { business_idx: 2, platform: 'google', reviewer_name: 'Emily L.', rating: 5, review_text: 'My new favorite coffee spot! The baristas really know their craft. The latte art is beautiful and the beans are perfectly roasted.', sentiment: 'positive' },
      { business_idx: 2, platform: 'google', reviewer_name: 'David K.', rating: 3, review_text: 'Decent coffee but nothing special. The pastries were stale. Nice ambiance for working though.', sentiment: 'neutral' },
      { business_idx: 4, platform: 'google', reviewer_name: 'Lisa T.', rating: 5, review_text: 'Best pastrami sandwich in the city! Generous portions and fresh ingredients. The pickles are homemade and delicious.', sentiment: 'positive' },
      { business_idx: 4, platform: 'google', reviewer_name: 'Chris P.', rating: 1, review_text: 'Terrible experience. Found a hair in my food and the manager didn\'t even apologize properly. Never coming back.', sentiment: 'negative' },
      { business_idx: 6, platform: 'google', reviewer_name: 'Amanda B.', rating: 5, review_text: 'The ribeye was cooked to perfection! Medium rare, just as I ordered. The wine selection is impressive too.', sentiment: 'positive' },
      { business_idx: 8, platform: 'google', reviewer_name: 'Carlos G.', rating: 4, review_text: 'Authentic Mexican flavors! The street tacos reminded me of my grandmother\'s cooking. Only wish the portions were bigger.', sentiment: 'positive' },
      { business_idx: 8, platform: 'google', reviewer_name: 'Nancy W.', rating: 2, review_text: 'Way too spicy for my taste and they didn\'t warn us. The guacamole was brown and clearly not fresh.', sentiment: 'negative' },
      { business_idx: 10, platform: 'google', reviewer_name: 'Tom H.', rating: 4, review_text: 'Solid pizza! The crust is crispy and the toppings are generous. Delivery was quick too.', sentiment: 'positive' },
      { business_idx: 10, platform: 'google', reviewer_name: 'Rachel F.', rating: 3, review_text: 'Average pizza, nothing memorable. The garlic knots were good though.', sentiment: 'neutral' },
      { business_idx: 12, platform: 'google', reviewer_name: 'James L.', rating: 5, review_text: 'The brisket melts in your mouth! Been to many BBQ joints but this one takes the crown. The mac and cheese is addictive.', sentiment: 'positive' },
      { business_idx: 12, platform: 'google', reviewer_name: 'Patricia N.', rating: 4, review_text: 'Great BBQ but the sides were just okay. The ribs were fall-off-the-bone tender though.', sentiment: 'positive' },
      { business_idx: 14, platform: 'google', reviewer_name: 'Robert K.', rating: 5, review_text: 'Best butter chicken in town! The naan is fresh out of the tandoor. The staff is very friendly and accommodating.', sentiment: 'positive' },

      // Yelp Reviews
      { business_idx: 1, platform: 'yelp', reviewer_name: 'Jennifer S.', rating: 5, review_text: 'Omakase experience was incredible! Chef crafted each piece with precision. Fresh fish, perfect rice temperature.', sentiment: 'positive' },
      { business_idx: 1, platform: 'yelp', reviewer_name: 'Michael T.', rating: 4, review_text: 'Great sushi but a bit pricey. The salmon sashimi was buttery smooth. Would recommend for special occasions.', sentiment: 'positive' },
      { business_idx: 1, platform: 'yelp', reviewer_name: 'Angela R.', rating: 2, review_text: 'Waited 45 minutes for our food even though the restaurant wasn\'t busy. The fish tasted off. Very disappointed.', sentiment: 'negative' },
      { business_idx: 3, platform: 'yelp', reviewer_name: 'Kevin M.', rating: 5, review_text: 'Finally a vegetarian restaurant that understands flavor! The mushroom risotto was earthy and satisfying.', sentiment: 'positive' },
      { business_idx: 3, platform: 'yelp', reviewer_name: 'Diana L.', rating: 3, review_text: 'Good options for vegetarians but portions are small for the price. The salads are fresh though.', sentiment: 'neutral' },
      { business_idx: 5, platform: 'yelp', reviewer_name: 'Steven C.', rating: 5, review_text: 'The lobster bisque is heavenly! Fresh catches daily and you can taste the difference. Ocean view is a bonus.', sentiment: 'positive' },
      { business_idx: 5, platform: 'yelp', reviewer_name: 'Michelle P.', rating: 1, review_text: 'Got food poisoning from the oysters. Spent the whole night sick. Will be reporting to health department.', sentiment: 'negative' },
      { business_idx: 7, platform: 'yelp', reviewer_name: 'Daniel B.', rating: 5, review_text: 'The croissants are flaky perfection! Better than what I had in Paris. The wedding cake they made was stunning.', sentiment: 'positive' },
      { business_idx: 7, platform: 'yelp', reviewer_name: 'Laura H.', rating: 4, review_text: 'Lovely pastries but they sell out fast. Got there at 2pm and most things were gone. Quality is top notch though.', sentiment: 'positive' },
      { business_idx: 9, platform: 'yelp', reviewer_name: 'Brandon J.', rating: 5, review_text: 'Best pancakes in Seattle! Fluffy, buttery, and the maple syrup is real. Worth the weekend wait.', sentiment: 'positive' },
      { business_idx: 9, platform: 'yelp', reviewer_name: 'Stephanie W.', rating: 2, review_text: 'Overrated and overpriced. The eggs benedict was soggy and the hollandaise was from a packet.', sentiment: 'negative' },
      { business_idx: 11, platform: 'yelp', reviewer_name: 'Andrew F.', rating: 5, review_text: 'Authentic Thai flavors! The pad thai is perfectly balanced and the green curry has real kick.', sentiment: 'positive' },
      { business_idx: 11, platform: 'yelp', reviewer_name: 'Nicole D.', rating: 4, review_text: 'Delicious food but the service was slow. The tom yum soup was spicy and flavorful. Will return.', sentiment: 'positive' },
      { business_idx: 13, platform: 'yelp', reviewer_name: 'Gregory M.', rating: 5, review_text: 'Transported me to Paris! The coq au vin was rich and the crème brûlée had the perfect caramelized top.', sentiment: 'positive' },
      { business_idx: 13, platform: 'yelp', reviewer_name: 'Catherine A.', rating: 3, review_text: 'Good French food but the portions are tiny. Left feeling hungry despite spending $80. Nice wine list.', sentiment: 'neutral' }
    ];

    for (const review of reviews) {
      const reviewDate = new Date();
      reviewDate.setDate(reviewDate.getDate() - Math.floor(Math.random() * 30));

      await pool.query(`
        INSERT INTO reviews (business_id, platform, reviewer_name, rating, review_text, review_date, sentiment, response_status)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
      `, [
        businessIds[review.business_idx],
        review.platform,
        review.reviewer_name,
        review.rating,
        review.review_text,
        reviewDate,
        review.sentiment,
        Math.random() > 0.5 ? 'pending' : 'draft'
      ]);
    }

    // Update review counts for businesses
    await pool.query(`
      UPDATE businesses b
      SET review_count = (SELECT COUNT(*) FROM reviews r WHERE r.business_id = b.id)
    `);
    console.log(`${reviews.length} reviews created`);

    // Seed Templates (15+ items)
    const templates = [
      { name: '5-Star Thank You', category: 'positive', tone: 'grateful', content: 'Thank you so much for your wonderful {rating}-star review, {reviewer_name}! We\'re thrilled that you enjoyed your experience with us. Your kind words mean a lot to our team. We can\'t wait to welcome you back soon!' },
      { name: 'Professional Positive Response', category: 'positive', tone: 'professional', content: 'Dear {reviewer_name}, thank you for taking the time to share your positive experience. We\'re delighted to hear you enjoyed {highlight}. Our team works hard to deliver excellence, and your feedback is greatly appreciated.' },
      { name: 'Friendly Thank You', category: 'positive', tone: 'friendly', content: 'Hey {reviewer_name}! Thanks a bunch for the awesome review! We\'re so happy you had a great time. See you again soon - next one\'s on us! 😊' },
      { name: 'Apology - Service Issue', category: 'apology', tone: 'apologetic', content: 'Dear {reviewer_name}, we sincerely apologize for the service issues you experienced. This is not up to our standards, and we take your feedback seriously. Please reach out to us directly so we can make this right.' },
      { name: 'Apology - Food Quality', category: 'apology', tone: 'apologetic', content: 'Thank you for your honest feedback, {reviewer_name}. We\'re truly sorry that the food quality didn\'t meet your expectations. We\'ve shared your concerns with our kitchen team and are taking immediate action.' },
      { name: 'Apology - Wait Time', category: 'apology', tone: 'apologetic', content: 'Dear {reviewer_name}, we apologize for the long wait you experienced. We understand your time is valuable, and we\'re implementing changes to improve our efficiency. We hope you\'ll give us another chance.' },
      { name: 'Neutral Response', category: 'neutral', tone: 'professional', content: 'Thank you for your feedback, {reviewer_name}. We appreciate you sharing your experience with us. We\'re always looking for ways to improve, and your input helps us do better.' },
      { name: 'Constructive Response', category: 'neutral', tone: 'professional', content: 'Dear {reviewer_name}, thank you for your balanced review. We\'re glad you enjoyed {positive_aspects} and we take note of your suggestions for improvement. We\'d love to see you again.' },
      { name: 'Recovery - Bad Experience', category: 'negative', tone: 'apologetic', content: 'Dear {reviewer_name}, we\'re deeply sorry to hear about your disappointing experience. This is not reflective of the standards we strive for. Please contact us at {contact} so we can personally address your concerns.' },
      { name: 'Recovery - Health Concern', category: 'negative', tone: 'apologetic', content: 'Dear {reviewer_name}, we take health and safety extremely seriously. We\'re very sorry to hear about your experience and would like to investigate this immediately. Please contact our manager directly at {contact}.' },
      { name: 'First Visit Thank You', category: 'thank_you', tone: 'friendly', content: 'Welcome to the family, {reviewer_name}! Thank you for choosing us for your first visit. We\'re so glad you enjoyed it and hope to become your new favorite spot!' },
      { name: 'Return Customer Appreciation', category: 'thank_you', tone: 'grateful', content: 'Dear {reviewer_name}, thank you for being a loyal customer! Your continued support means the world to us. We always look forward to seeing you!' },
      { name: 'Special Occasion Thank You', category: 'thank_you', tone: 'grateful', content: 'Thank you for celebrating your special occasion with us, {reviewer_name}! It was our pleasure to be part of your {occasion}. Wishing you many more happy memories!' },
      { name: 'Quick Professional Response', category: 'positive', tone: 'professional', content: 'Thank you for your kind review, {reviewer_name}. We\'re pleased you had a positive experience. We look forward to serving you again.' },
      { name: 'Detailed Apology', category: 'apology', tone: 'apologetic', content: 'Dear {reviewer_name}, I personally want to apologize for your recent experience. After reviewing what happened, I understand why you\'re disappointed. We\'ve addressed this with our team and would like to offer you {offer} on your next visit. Please email me directly at {email}.' }
    ];

    for (const template of templates) {
      await pool.query(`
        INSERT INTO templates (user_id, name, category, content, tone, use_count)
        VALUES ($1, $2, $3, $4, $5, $6)
      `, [userId, template.name, template.category, template.content, template.tone, Math.floor(Math.random() * 50)]);
    }
    console.log(`${templates.length} templates created`);

    // Seed Settings (15+ items)
    const settings = [
      { key: 'default_tone', value: 'professional' },
      { key: 'auto_analyze_sentiment', value: 'true' },
      { key: 'notify_new_reviews', value: 'true' },
      { key: 'notify_negative_reviews', value: 'true' },
      { key: 'email_notifications', value: 'true' },
      { key: 'notification_email', value: 'admin@reviewmanager.com' },
      { key: 'response_language', value: 'en' },
      { key: 'include_business_name', value: 'true' },
      { key: 'include_signature', value: 'true' },
      { key: 'signature_text', value: 'Best regards,\nThe Management Team' },
      { key: 'auto_approve_positive', value: 'false' },
      { key: 'minimum_rating_threshold', value: '3' },
      { key: 'max_response_length', value: '500' },
      { key: 'ai_model_preference', value: 'gpt-3.5-turbo' },
      { key: 'theme', value: 'light' }
    ];

    for (const setting of settings) {
      await pool.query(`
        INSERT INTO settings (user_id, setting_key, setting_value)
        VALUES ($1, $2, $3)
      `, [userId, setting.key, setting.value]);
    }
    console.log(`${settings.length} settings created`);

    // Create some response drafts (15+ items)
    const reviewsWithDrafts = await pool.query('SELECT id, reviewer_name, rating FROM reviews LIMIT 15');
    const draftTones = ['professional', 'friendly', 'apologetic', 'grateful'];
    const draftTemplates = [
      'Thank you for your review, {name}! We appreciate your feedback and look forward to serving you again.',
      'Dear {name}, we truly value your {rating}-star review. Your satisfaction is our priority.',
      'Hi {name}! Thanks for taking the time to share your experience. We\'re always working to improve!',
      '{name}, your feedback means a lot to us. We hope to see you back soon!',
      'We appreciate you choosing us, {name}. Thank you for the wonderful review!'
    ];

    for (let i = 0; i < reviewsWithDrafts.rows.length; i++) {
      const review = reviewsWithDrafts.rows[i];
      const tone = draftTones[i % draftTones.length];
      const template = draftTemplates[i % draftTemplates.length]
        .replace('{name}', review.reviewer_name)
        .replace('{rating}', review.rating);

      await pool.query(`
        INSERT INTO response_drafts (review_id, draft_text, tone, is_approved, is_sent)
        VALUES ($1, $2, $3, $4, $5)
      `, [review.id, template, tone, i < 5, i < 3]);
    }
    console.log('15 response drafts created');

    // ==================== SEED NEW FEATURES ====================

    // 1. Fake Review Detections (15+ items)
    const fakeReviews = [
      { review_text: 'BEST PRODUCT EVER!!! You MUST buy this NOW! I bought 10 already! AMAZING AMAZING AMAZING!', reviewer_name: 'HappyCustomer123', platform: 'amazon', fake_probability: 85.5, confidence_score: 90.0, red_flags: ['Excessive capitalization', 'Repetitive language', 'Generic username'], ai_analysis: 'High probability of fake review due to excessive enthusiasm and lack of specific details.', status: 'analyzed', is_fake: true },
      { review_text: 'Product arrived damaged. Customer service was unhelpful. Very disappointed with my purchase.', reviewer_name: 'Jane Smith', platform: 'amazon', fake_probability: 15.0, confidence_score: 85.0, red_flags: [], ai_analysis: 'Appears to be genuine negative review with specific complaint.', status: 'verified', is_fake: false },
      { review_text: 'good product fast shipping recommend', reviewer_name: 'buyer2847', platform: 'ebay', fake_probability: 65.0, confidence_score: 70.0, red_flags: ['Very short', 'No punctuation', 'Generic comment'], ai_analysis: 'Suspicious due to brevity and lack of detail, but inconclusive.', status: 'pending' },
      { review_text: 'This restaurant changed my life! The food was so good I cried tears of joy. Every dish was perfection incarnate!', reviewer_name: 'FoodLover99', platform: 'yelp', fake_probability: 72.0, confidence_score: 78.0, red_flags: ['Over-the-top praise', 'Hyperbolic language', 'No specific dishes mentioned'], ai_analysis: 'Likely exaggerated or potentially incentivized review.', status: 'analyzed', is_fake: null },
      { review_text: 'The steak was cooked medium-rare as requested. Server was attentive but not intrusive. Would recommend the wine pairing.', reviewer_name: 'Michael Chen', platform: 'google', fake_probability: 8.0, confidence_score: 92.0, red_flags: [], ai_analysis: 'Genuine review with specific details about the dining experience.', status: 'verified', is_fake: false },
      { review_text: 'I never write reviews but had to for this! INCREDIBLE! Will buy again! Perfect! 5 STARS!', reviewer_name: 'FirstTimeReviewer', platform: 'amazon', fake_probability: 78.0, confidence_score: 82.0, red_flags: ['Claims never reviews', 'Multiple exclamations', 'No product details'], ai_analysis: 'Pattern consistent with incentivized or fake review.', status: 'analyzed', is_fake: true },
      { review_text: 'Decent product for the price. Works as described but packaging could be better.', reviewer_name: 'Robert Johnson', platform: 'amazon', fake_probability: 12.0, confidence_score: 88.0, red_flags: [], ai_analysis: 'Balanced, specific review appears genuine.', status: 'verified', is_fake: false },
      { review_text: 'worst product ever dont buy waste of money seller is scammer', reviewer_name: 'angry_buyer', platform: 'ebay', fake_probability: 55.0, confidence_score: 65.0, red_flags: ['All lowercase', 'No punctuation', 'Extreme language'], ai_analysis: 'Could be genuine frustration or competitor attack. Inconclusive.', status: 'pending' },
      { review_text: 'My wife loves this! Bought it for her birthday and she uses it every day. Great quality materials.', reviewer_name: 'David Williams', platform: 'amazon', fake_probability: 18.0, confidence_score: 85.0, red_flags: [], ai_analysis: 'Personal context and specific use case indicate genuine review.', status: 'verified', is_fake: false },
      { review_text: 'Product exactly as described! Fast shipping! Great seller! A++++ Would buy again!', reviewer_name: 'quickbuyer2024', platform: 'ebay', fake_probability: 60.0, confidence_score: 72.0, red_flags: ['Formulaic structure', 'Generic praise', 'Suspicious username format'], ai_analysis: 'Matches pattern of template-based fake reviews.', status: 'analyzed', is_fake: true },
      { review_text: 'Been using this software for 3 months now. Saves me about 2 hours per week on reports.', reviewer_name: 'Sarah Martinez', platform: 'g2', fake_probability: 10.0, confidence_score: 90.0, red_flags: [], ai_analysis: 'Specific timeframe and quantified benefits suggest authentic review.', status: 'verified', is_fake: false },
      { review_text: 'This is the best thing since sliced bread! Everyone needs this in their life! Game changer!', reviewer_name: 'TrueFan2024', platform: 'amazon', fake_probability: 70.0, confidence_score: 75.0, red_flags: ['Cliche expressions', 'No specifics', 'Overly enthusiastic'], ai_analysis: 'Lacks substance typical of genuine reviews.', status: 'analyzed', is_fake: null },
      { review_text: 'Good but not great. The battery life could be better, lasts about 4 hours with heavy use.', reviewer_name: 'TechReviewer', platform: 'amazon', fake_probability: 5.0, confidence_score: 95.0, red_flags: [], ai_analysis: 'Balanced criticism with specific metrics indicates genuine feedback.', status: 'verified', is_fake: false },
      { review_text: 'Ordered 5 of these! Giving as gifts! Everyone will love them! HIGHLY RECOMMEND!', reviewer_name: 'GiftGiver88', platform: 'amazon', fake_probability: 68.0, confidence_score: 74.0, red_flags: ['Bulk purchase claim', 'No product details', 'Excessive enthusiasm'], ai_analysis: 'Pattern suggests potential review manipulation.', status: 'pending' },
      { review_text: 'After 6 months of use, I can confirm this holds up well. Minor wear on edges but overall satisfied.', reviewer_name: 'Long_Term_User', platform: 'amazon', fake_probability: 8.0, confidence_score: 93.0, red_flags: [], ai_analysis: 'Long-term usage feedback with honest assessment of wear indicates genuine review.', status: 'verified', is_fake: false },
      { review_text: 'DO NOT BUY FROM COMPETITOR X! This product is SO much better! Trust me!', reviewer_name: 'SmartShopper', platform: 'amazon', fake_probability: 82.0, confidence_score: 88.0, red_flags: ['Mentions competitor', 'Confrontational tone', 'Vague praise'], ai_analysis: 'Likely competitor attack or paid review based on comparative language.', status: 'analyzed', is_fake: true }
    ];

    for (const fr of fakeReviews) {
      await pool.query(`
        INSERT INTO fake_review_detections (review_text, reviewer_name, platform, fake_probability, confidence_score, red_flags, ai_analysis, status, is_fake)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
      `, [fr.review_text, fr.reviewer_name, fr.platform, fr.fake_probability, fr.confidence_score, fr.red_flags, fr.ai_analysis, fr.status, fr.is_fake]);
    }
    console.log(`${fakeReviews.length} fake review detections created`);

    // 2. Review Summaries (15+ items)
    const reviewSummaries = [
      { product_name: 'Wireless Bluetooth Headphones Pro', product_category: 'Electronics', total_reviews: 1247, average_rating: 4.3, summary_text: 'Customers praise the sound quality and comfortable fit, though some note limited battery life.', pros: ['Excellent sound quality', 'Comfortable for long use', 'Good noise cancellation'], cons: ['Battery lasts only 6 hours', 'Expensive', 'No wired option'], common_themes: ['Sound quality', 'Comfort', 'Battery', 'Price'], sentiment_breakdown: { positive: 72, neutral: 18, negative: 10 }, ai_insights: 'Strong product with room for battery improvement. Consider highlighting comfort in marketing.' },
      { product_name: 'Organic Green Tea Collection', product_category: 'Food & Beverage', total_reviews: 523, average_rating: 4.6, summary_text: 'Highly rated for authentic taste and quality packaging. Some find it pricey.', pros: ['Authentic flavor', 'Beautiful packaging', 'Organic certified'], cons: ['Premium pricing', 'Limited variety', 'Shipping delays'], common_themes: ['Taste', 'Quality', 'Price', 'Packaging'], sentiment_breakdown: { positive: 85, neutral: 10, negative: 5 }, ai_insights: 'Premium positioning is working. Bundle deals could address price concerns.' },
      { product_name: 'Smart Home Security Camera', product_category: 'Home & Garden', total_reviews: 2891, average_rating: 4.1, summary_text: 'Good video quality and easy setup, but app reliability is a concern.', pros: ['Crystal clear video', 'Easy installation', 'Night vision works well'], cons: ['App crashes frequently', 'Subscription required', 'Privacy concerns'], common_themes: ['Video quality', 'App', 'Setup', 'Subscription'], sentiment_breakdown: { positive: 65, neutral: 20, negative: 15 }, ai_insights: 'App stability is the primary improvement area. Address in next software update.' },
      { product_name: 'Professional Chef Knife Set', product_category: 'Kitchen', total_reviews: 876, average_rating: 4.7, summary_text: 'Exceptional sharpness and balance praised by home cooks and professionals alike.', pros: ['Razor sharp', 'Well balanced', 'Beautiful design', 'Durable'], cons: ['Requires careful maintenance', 'Heavy for some users', 'Expensive'], common_themes: ['Sharpness', 'Quality', 'Design', 'Maintenance'], sentiment_breakdown: { positive: 88, neutral: 8, negative: 4 }, ai_insights: 'Include care instructions to address maintenance concerns. Premium pricing justified by quality.' },
      { product_name: 'Yoga Mat Extra Thick', product_category: 'Sports & Fitness', total_reviews: 1456, average_rating: 4.4, summary_text: 'Loved for cushioning and grip, though some find it too heavy to carry.', pros: ['Excellent cushioning', 'Non-slip surface', 'Eco-friendly material'], cons: ['Heavy for travel', 'Strong initial odor', 'Takes time to break in'], common_themes: ['Comfort', 'Grip', 'Weight', 'Smell'], sentiment_breakdown: { positive: 78, neutral: 15, negative: 7 }, ai_insights: 'Consider lighter travel version. Address off-gassing in product description.' },
      { product_name: 'Moisturizing Face Cream SPF30', product_category: 'Beauty', total_reviews: 2134, average_rating: 4.2, summary_text: 'Effective moisturizing with sun protection, but some experience breakouts.', pros: ['Great moisturizer', 'SPF protection', 'Light texture', 'Pleasant scent'], cons: ['Causes breakouts for some', 'White cast on darker skin', 'Pricey'], common_themes: ['Moisturizing', 'SPF', 'Skin reaction', 'Texture'], sentiment_breakdown: { positive: 70, neutral: 18, negative: 12 }, ai_insights: 'Consider developing a sensitive skin variant. Address white cast issue for inclusive marketing.' },
      { product_name: 'Standing Desk Converter', product_category: 'Office', total_reviews: 967, average_rating: 4.5, summary_text: 'Sturdy and easy to adjust, though assembly instructions could be clearer.', pros: ['Solid construction', 'Smooth height adjustment', 'Good keyboard tray'], cons: ['Confusing assembly', 'Takes up desk space', 'Wobbles slightly at max height'], common_themes: ['Build quality', 'Adjustment', 'Assembly', 'Space'], sentiment_breakdown: { positive: 80, neutral: 12, negative: 8 }, ai_insights: 'Create video assembly guide. Consider more compact model for smaller desks.' },
      { product_name: 'Kids Educational Tablet', product_category: 'Toys', total_reviews: 1823, average_rating: 4.0, summary_text: 'Educational content is great, but durability concerns for rough play.', pros: ['Educational apps', 'Parental controls', 'Kid-friendly interface'], cons: ['Screen scratches easily', 'Limited storage', 'Battery drains fast'], common_themes: ['Education', 'Durability', 'Battery', 'Content'], sentiment_breakdown: { positive: 62, neutral: 23, negative: 15 }, ai_insights: 'Bundle with screen protector. Expand educational content library.' },
      { product_name: 'Portable Blender USB', product_category: 'Kitchen', total_reviews: 3421, average_rating: 4.1, summary_text: 'Convenient for travel and simple smoothies, but struggles with frozen fruit.', pros: ['Highly portable', 'USB charging', 'Easy to clean'], cons: ['Weak motor', 'Small capacity', 'Leaks if overfilled'], common_themes: ['Portability', 'Power', 'Capacity', 'Leaking'], sentiment_breakdown: { positive: 68, neutral: 20, negative: 12 }, ai_insights: 'Upgrade motor in next version. Add fill line to prevent leaking.' },
      { product_name: 'Memory Foam Pillow', product_category: 'Home', total_reviews: 2567, average_rating: 4.3, summary_text: 'Great neck support once broken in, initial chemical smell noted.', pros: ['Excellent support', 'Maintains shape', 'Cooling gel works'], cons: ['Strong initial smell', 'Takes time to adjust', 'Cover not machine washable'], common_themes: ['Support', 'Smell', 'Comfort', 'Washability'], sentiment_breakdown: { positive: 75, neutral: 15, negative: 10 }, ai_insights: 'Air out before packaging. Make cover machine washable in next version.' },
      { product_name: 'Wireless Car Charger Mount', product_category: 'Automotive', total_reviews: 1678, average_rating: 4.2, summary_text: 'Fast charging and secure grip, but some compatibility issues with cases.', pros: ['Fast charging', 'Secure grip', 'Easy one-hand operation'], cons: ['Case compatibility issues', 'Gets warm', 'Suction cup weakens'], common_themes: ['Charging speed', 'Mount security', 'Compatibility', 'Heat'], sentiment_breakdown: { positive: 72, neutral: 18, negative: 10 }, ai_insights: 'Expand case compatibility list. Improve heat dissipation in design.' },
      { product_name: 'Natural Dog Treats Variety Pack', product_category: 'Pet Supplies', total_reviews: 987, average_rating: 4.8, summary_text: 'Dogs love them! All-natural ingredients appreciated by health-conscious owners.', pros: ['Dogs love the taste', 'Natural ingredients', 'Good variety', 'Resealable packaging'], cons: ['Expensive per treat', 'Some treats crumble easily', 'Smaller than expected'], common_themes: ['Taste', 'Ingredients', 'Price', 'Size'], sentiment_breakdown: { positive: 92, neutral: 5, negative: 3 }, ai_insights: 'Premium pet market growing. Consider subscription model for repeat purchases.' },
      { product_name: 'Resistance Bands Set', product_category: 'Sports & Fitness', total_reviews: 4532, average_rating: 4.4, summary_text: 'Great for home workouts and travel. Durable bands with helpful exercise guide.', pros: ['Durable material', 'Multiple resistance levels', 'Includes guide', 'Compact storage'], cons: ['Handles could be softer', 'Latex smell', 'Limited heavy resistance'], common_themes: ['Durability', 'Versatility', 'Comfort', 'Resistance levels'], sentiment_breakdown: { positive: 80, neutral: 14, negative: 6 }, ai_insights: 'Add heavier resistance option for advanced users. Consider foam handles.' },
      { product_name: 'Smart Water Bottle', product_category: 'Health', total_reviews: 743, average_rating: 3.9, summary_text: 'Helpful hydration reminders, but sync issues with health apps frustrate users.', pros: ['Tracks water intake', 'LED reminders', 'Good insulation'], cons: ['App sync problems', 'Battery replacement difficult', 'Expensive'], common_themes: ['Tracking', 'App', 'Battery', 'Price'], sentiment_breakdown: { positive: 58, neutral: 25, negative: 17 }, ai_insights: 'Priority: fix app synchronization. Consider rechargeable battery option.' },
      { product_name: 'Vintage Style Record Player', product_category: 'Electronics', total_reviews: 1234, average_rating: 4.5, summary_text: 'Beautiful aesthetics with surprisingly good sound for the price point.', pros: ['Gorgeous design', 'Good sound quality', 'Bluetooth capability', 'Built-in speakers'], cons: ['Plastic components', 'No dust cover included', 'Limited EQ options'], common_themes: ['Design', 'Sound', 'Features', 'Build quality'], sentiment_breakdown: { positive: 82, neutral: 12, negative: 6 }, ai_insights: 'Vintage aesthetic resonates strongly. Bundle dust cover to address common complaint.' },
      { product_name: 'Meal Prep Containers 20-Pack', product_category: 'Kitchen', total_reviews: 5678, average_rating: 4.6, summary_text: 'Excellent value with leak-proof design. Perfect for weekly meal prep.', pros: ['Leak-proof', 'Microwave safe', 'Stackable', 'Great value'], cons: ['Lids can warp in dishwasher', 'Stains from tomato sauce', 'Limited compartment options'], common_themes: ['Leak-proof', 'Value', 'Durability', 'Cleaning'], sentiment_breakdown: { positive: 85, neutral: 10, negative: 5 }, ai_insights: 'Best seller potential. Create stain-resistant version for sauce-heavy meals.' }
    ];

    for (const rs of reviewSummaries) {
      await pool.query(`
        INSERT INTO review_summaries (product_name, product_category, total_reviews, average_rating, summary_text, pros, cons, common_themes, sentiment_breakdown, ai_insights)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
      `, [rs.product_name, rs.product_category, rs.total_reviews, rs.average_rating, rs.summary_text, rs.pros, rs.cons, rs.common_themes, rs.sentiment_breakdown, rs.ai_insights]);
    }
    console.log(`${reviewSummaries.length} review summaries created`);

    // 3. Trend Analyses (15+ items)
    const trendAnalyses = [
      { analysis_name: 'Q4 2024 Restaurant Performance', business_name: 'Bella Italia Restaurant', date_range_start: '2024-10-01', date_range_end: '2024-12-31', trend_direction: 'improving', sentiment_change: 8.5, emerging_topics: ['New menu items', 'Weekend brunch', 'Wine selection'], declining_topics: ['Wait times', 'Parking'], seasonal_patterns: { pattern: 'Holiday spike', peak_periods: ['December'], low_periods: ['January'] }, ai_prediction: 'Continued growth expected with new menu success.', recommendations: ['Expand brunch hours', 'Add valet parking'] },
      { analysis_name: 'Summer 2024 Coffee Shop Analysis', business_name: 'Sunrise Cafe', date_range_start: '2024-06-01', date_range_end: '2024-08-31', trend_direction: 'stable', sentiment_change: 2.1, emerging_topics: ['Cold brew', 'Outdoor seating', 'Vegan options'], declining_topics: ['Indoor AC'], seasonal_patterns: { pattern: 'Summer preference', peak_periods: ['July'], low_periods: ['August vacation'] }, ai_prediction: 'Stable performance with opportunity in cold beverages.', recommendations: ['Promote cold drinks', 'Add more vegan pastries'] },
      { analysis_name: 'Annual Review - Tech Retailer', business_name: 'ElectroMart', date_range_start: '2024-01-01', date_range_end: '2024-12-31', trend_direction: 'declining', sentiment_change: -12.3, emerging_topics: ['Online competitors', 'Price matching'], declining_topics: ['In-store service', 'Product knowledge'], seasonal_patterns: { pattern: 'Black Friday peak', peak_periods: ['November'], low_periods: ['February'] }, ai_prediction: 'Need intervention to reverse negative trend.', recommendations: ['Staff training urgently needed', 'Implement price match guarantee', 'Improve online presence'] },
      { analysis_name: 'Post-Renovation Analysis', business_name: 'Downtown Deli', date_range_start: '2024-09-01', date_range_end: '2024-11-30', trend_direction: 'improving', sentiment_change: 15.7, emerging_topics: ['New interior', 'Expanded menu', 'Better seating'], declining_topics: [], seasonal_patterns: { pattern: 'Steady growth', peak_periods: ['Lunch hours'], low_periods: ['Early morning'] }, ai_prediction: 'Renovation investment paying off. Momentum should continue.', recommendations: ['Promote new look on social media', 'Consider breakfast expansion'] },
      { analysis_name: 'Competitor Entry Impact', business_name: 'Tokyo Sushi Bar', date_range_start: '2024-07-01', date_range_end: '2024-09-30', trend_direction: 'declining', sentiment_change: -6.8, emerging_topics: ['Pricing concerns', 'Comparing to new sushi place'], declining_topics: ['Unique experience'], seasonal_patterns: { pattern: 'Competition impact', peak_periods: ['Weekends'], low_periods: ['Weekday dinners'] }, ai_prediction: 'Market share at risk. Differentiation needed.', recommendations: ['Launch loyalty program', 'Emphasize authentic experience', 'Consider omakase nights'] },
      { analysis_name: 'First Year Performance', business_name: 'Green Garden Bistro', date_range_start: '2024-01-01', date_range_end: '2024-12-31', trend_direction: 'improving', sentiment_change: 22.4, emerging_topics: ['Word of mouth', 'Instagram presence', 'Vegan community'], declining_topics: [], seasonal_patterns: { pattern: 'Steady growth', peak_periods: ['Veganuary', 'Earth Day'], low_periods: ['Summer vacations'] }, ai_prediction: 'Excellent trajectory for new restaurant. Brand building successful.', recommendations: ['Expand to weekend brunch', 'Partner with local farms'] },
      { analysis_name: 'Service Speed Initiative', business_name: 'Taco Fiesta', date_range_start: '2024-04-01', date_range_end: '2024-06-30', trend_direction: 'improving', sentiment_change: 11.2, emerging_topics: ['Faster service', 'Online ordering', 'Accuracy'], declining_topics: ['Long waits', 'Order mistakes'], seasonal_patterns: { pattern: 'Lunch rush', peak_periods: ['Lunch'], low_periods: ['Late evening'] }, ai_prediction: 'Service improvements showing clear positive impact.', recommendations: ['Continue staff training', 'Maintain quality with speed'] },
      { analysis_name: 'Pandemic Recovery Tracking', business_name: 'French Quarter Bistro', date_range_start: '2024-01-01', date_range_end: '2024-06-30', trend_direction: 'improving', sentiment_change: 18.9, emerging_topics: ['Full capacity', 'Special events', 'Wine dinners'], declining_topics: ['COVID concerns', 'Limited hours'], seasonal_patterns: { pattern: 'Event-driven', peak_periods: ['Valentine\'s', 'Mother\'s Day'], low_periods: ['Post-holiday January'] }, ai_prediction: 'Full recovery achieved. Ready for growth phase.', recommendations: ['Increase special event offerings', 'Launch catering service'] },
      { analysis_name: 'Menu Change Impact Study', business_name: 'Indian Spice House', date_range_start: '2024-08-01', date_range_end: '2024-10-31', trend_direction: 'stable', sentiment_change: -1.5, emerging_topics: ['New dishes', 'Regional specialties'], declining_topics: ['Removed favorites', 'Portion sizes'], seasonal_patterns: { pattern: 'Mixed response', peak_periods: ['Weekends'], low_periods: ['Monday-Tuesday'] }, ai_prediction: 'Menu change neutral to slightly negative. Monitor closely.', recommendations: ['Consider bringing back top removed items', 'Adjust portion sizes'] },
      { analysis_name: 'Delivery Service Expansion', business_name: 'Pizza Paradise', date_range_start: '2024-05-01', date_range_end: '2024-07-31', trend_direction: 'improving', sentiment_change: 9.8, emerging_topics: ['Delivery speed', 'Hot pizza', 'Driver friendliness'], declining_topics: ['Cold delivery', 'Missing items'], seasonal_patterns: { pattern: 'Weekend peak', peak_periods: ['Friday-Saturday'], low_periods: ['Monday-Wednesday'] }, ai_prediction: 'Delivery improvements driving growth. Continue investment.', recommendations: ['Expand delivery radius', 'Add more drivers on weekends'] },
      { analysis_name: 'Staff Turnover Effect', business_name: 'Mountain View Steakhouse', date_range_start: '2024-03-01', date_range_end: '2024-05-31', trend_direction: 'declining', sentiment_change: -8.4, emerging_topics: ['New staff inexperienced', 'Inconsistent service'], declining_topics: ['Personal touch', 'Regular customer recognition'], seasonal_patterns: { pattern: 'Decline during training', peak_periods: ['Pre-turnover'], low_periods: ['Training period'] }, ai_prediction: 'Training period impacting reviews. Should recover.', recommendations: ['Accelerate training program', 'Pair new staff with experienced mentors'] },
      { analysis_name: 'Social Media Campaign Results', business_name: 'Sweet Treats Bakery', date_range_start: '2024-09-01', date_range_end: '2024-11-30', trend_direction: 'improving', sentiment_change: 14.3, emerging_topics: ['Instagram worthy', 'Birthday cakes', 'Custom orders'], declining_topics: [], seasonal_patterns: { pattern: 'Event-driven', peak_periods: ['Holidays', 'Graduation season'], low_periods: ['Post-holiday'] }, ai_prediction: 'Social media driving significant new business.', recommendations: ['Continue influencer partnerships', 'Launch TikTok presence'] },
      { analysis_name: 'Price Increase Impact', business_name: 'Coastal Seafood Grill', date_range_start: '2024-06-01', date_range_end: '2024-08-31', trend_direction: 'stable', sentiment_change: -3.2, emerging_topics: ['Value concerns', 'Portion vs price'], declining_topics: ['Best value'], seasonal_patterns: { pattern: 'Tourist season', peak_periods: ['July-August'], low_periods: ['September'] }, ai_prediction: 'Price sensitivity noted but not significantly impacting volume.', recommendations: ['Add value menu options', 'Emphasize quality to justify pricing'] },
      { analysis_name: 'New Location Performance', business_name: 'The Breakfast Club - Downtown', date_range_start: '2024-10-01', date_range_end: '2024-12-31', trend_direction: 'improving', sentiment_change: 25.6, emerging_topics: ['Convenient location', 'Same quality', 'Less wait'], declining_topics: [], seasonal_patterns: { pattern: 'Weekday strong', peak_periods: ['Weekday mornings'], low_periods: ['Weekend evenings'] }, ai_prediction: 'New location exceeding expectations. Consider third location.', recommendations: ['Capture business breakfast market', 'Add catering services'] },
      { analysis_name: 'Health Code Recovery', business_name: 'Thai Orchid', date_range_start: '2024-02-01', date_range_end: '2024-04-30', trend_direction: 'improving', sentiment_change: 31.2, emerging_topics: ['Cleanliness improved', 'New management', 'Trust restored'], declining_topics: ['Health concerns', 'Past issues'], seasonal_patterns: { pattern: 'Recovery curve', peak_periods: ['Post-resolution'], low_periods: ['During incident'] }, ai_prediction: 'Crisis successfully managed. Brand reputation recovering well.', recommendations: ['Continue transparency about improvements', 'Invite health re-inspection publicity'] },
      { analysis_name: 'BBQ Competition Season', business_name: 'BBQ Pitmaster', date_range_start: '2024-05-01', date_range_end: '2024-09-30', trend_direction: 'improving', sentiment_change: 12.8, emerging_topics: ['Award winning', 'Competition circuit', 'New rubs'], declining_topics: [], seasonal_patterns: { pattern: 'Competition peaks', peak_periods: ['July 4th', 'Labor Day'], low_periods: ['Early May'] }, ai_prediction: 'Competition wins driving significant brand value.', recommendations: ['Leverage awards in marketing', 'Sell competition rubs retail'] }
    ];

    for (const ta of trendAnalyses) {
      await pool.query(`
        INSERT INTO trend_analyses (analysis_name, business_name, date_range_start, date_range_end, trend_direction, sentiment_change, emerging_topics, declining_topics, seasonal_patterns, ai_prediction, recommendations)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
      `, [ta.analysis_name, ta.business_name, ta.date_range_start, ta.date_range_end, ta.trend_direction, ta.sentiment_change, ta.emerging_topics, ta.declining_topics, ta.seasonal_patterns, ta.ai_prediction, ta.recommendations]);
    }
    console.log(`${trendAnalyses.length} trend analyses created`);

    // 4. Counterfeit Detections (15+ items)
    const counterfeitDetections = [
      { product_name: 'Designer Handbag Model XL', seller_name: 'LuxuryDeals2024', platform: 'amazon', review_count: 45, risk_level: 'high', risk_score: 85.0, warning_signs: ['Price 70% below retail', 'Multiple authenticity complaints', 'Seller has no brand authorization'], suspicious_reviews: ['Stitching is completely different from my authentic one', 'Logo is crooked and wrong font', 'Smells like chemicals, not leather'], ai_analysis: 'High probability of counterfeit. Multiple indicators of fake luxury goods.', status: 'flagged', action_taken: 'Reported to marketplace' },
      { product_name: 'Wireless Earbuds Pro Max', seller_name: 'TechBargains', platform: 'ebay', review_count: 128, risk_level: 'medium', risk_score: 55.0, warning_signs: ['Inconsistent packaging reports', 'Sound quality varies by unit', 'No warranty honored'], suspicious_reviews: ['Box was different than official', 'Serial number not recognized by manufacturer'], ai_analysis: 'Mixed signals - could be gray market or counterfeit. Further investigation needed.', status: 'monitoring', action_taken: null },
      { product_name: 'Organic Vitamin D Supplements', seller_name: 'HealthyLife365', platform: 'amazon', review_count: 89, risk_level: 'critical', risk_score: 92.0, warning_signs: ['FDA warning match', 'Lab test reports inconsistent', 'Different pill appearance'], suspicious_reviews: ['Pills look different than before', 'Got sick after taking these', 'Bottle seal was broken'], ai_analysis: 'Critical risk - potential health hazard. Matches FDA counterfeit warning profile.', status: 'escalated', action_taken: 'FDA report filed' },
      { product_name: 'Professional Running Shoes', seller_name: 'SportsDirect_Outlet', platform: 'amazon', review_count: 234, risk_level: 'medium', risk_score: 48.0, warning_signs: ['Sizing inconsistencies', 'Some quality complaints', 'Price below authorized dealer'], suspicious_reviews: ['Glue showing on sides', 'Fell apart after 2 weeks'], ai_analysis: 'Possibly factory seconds or unauthorized production run. Not definitive counterfeit.', status: 'monitoring', action_taken: null },
      { product_name: 'Luxury Watch Classic Series', seller_name: 'WatchDeals_Premium', platform: 'ebay', review_count: 23, risk_level: 'high', risk_score: 88.0, warning_signs: ['No original box/papers', 'Movement sounds different', 'Weight feels off'], suspicious_reviews: ['Jeweler confirmed it is fake', 'Second hand stutters instead of sweeps', 'Crystal scratches easily'], ai_analysis: 'High confidence counterfeit. Movement type mismatch is definitive indicator.', status: 'flagged', action_taken: 'Seller reported' },
      { product_name: 'Premium Coffee Beans 1kg', seller_name: 'CoffeeLoversCo', platform: 'amazon', review_count: 156, risk_level: 'low', risk_score: 15.0, warning_signs: [], suspicious_reviews: [], ai_analysis: 'No counterfeit indicators found. Legitimate authorized seller with consistent quality.', status: 'verified', action_taken: 'Marked as authentic' },
      { product_name: 'Designer Sunglasses Limited Ed', seller_name: 'ShadesWorld', platform: 'amazon', review_count: 67, risk_level: 'high', risk_score: 78.0, warning_signs: ['No brand authorization', 'Case quality poor', 'UV protection unverified'], suspicious_reviews: ['Clearly fake compared to store version', 'Lenses have no UV coating', 'Hinges broke first week'], ai_analysis: 'Likely counterfeit. Multiple quality and authenticity indicators.', status: 'flagged', action_taken: 'Brand notified' },
      { product_name: 'Smartphone Battery Replacement', seller_name: 'PhonePartsPro', platform: 'ebay', review_count: 312, risk_level: 'medium', risk_score: 52.0, warning_signs: ['Capacity lower than stated', 'Some swelling reports', 'Not OEM certified'], suspicious_reviews: ['Died after 3 months', 'Capacity is only 60% of claimed', 'Phone overheats with this battery'], ai_analysis: 'Quality concerns present. May be third-party not counterfeit, but safety risk exists.', status: 'monitoring', action_taken: 'Safety review initiated' },
      { product_name: 'Skincare Serum Anti-Aging', seller_name: 'BeautySecrets', platform: 'amazon', review_count: 198, risk_level: 'high', risk_score: 82.0, warning_signs: ['Texture differs from official', 'Batch numbers not verifiable', 'Allergic reactions reported'], suspicious_reviews: ['Caused breakout unlike real version', 'Consistency is watery not gel', 'Packaging print quality poor'], ai_analysis: 'High risk counterfeit. Formulation clearly different from authentic product.', status: 'flagged', action_taken: 'Health authority notified' },
      { product_name: 'Gaming Console Controller', seller_name: 'GamerGear_Official', platform: 'amazon', review_count: 445, risk_level: 'low', risk_score: 22.0, warning_signs: ['Price slightly below retail'], suspicious_reviews: ['Works great but box was different'], ai_analysis: 'Likely legitimate gray market import. Minor packaging differences noted.', status: 'verified', action_taken: null },
      { product_name: 'Premium Olive Oil Extra Virgin', seller_name: 'MediterraneanImports', platform: 'amazon', review_count: 87, risk_level: 'medium', risk_score: 45.0, warning_signs: ['Taste inconsistency reports', 'Label translation errors', 'Harvest date unclear'], suspicious_reviews: ['Doesnt taste like olive oil', 'Much lighter color than usual', 'Smoke point seems lower'], ai_analysis: 'Possible adulteration or mislabeling. Common issue in olive oil market.', status: 'monitoring', action_taken: 'Lab testing requested' },
      { product_name: 'Luxury Perfume 100ml', seller_name: 'FragranceOutlet', platform: 'ebay', review_count: 156, risk_level: 'high', risk_score: 75.0, warning_signs: ['Longevity complaints', 'Batch code issues', 'Cellophane seal different'], suspicious_reviews: ['Scent fades in 1 hour', 'My nose knows this is fake', 'Atomizer broke immediately'], ai_analysis: 'High probability counterfeit. Performance significantly below authentic benchmarks.', status: 'flagged', action_taken: 'Reported to brand' },
      { product_name: 'Memory Card 256GB', seller_name: 'StorageKing', platform: 'amazon', review_count: 523, risk_level: 'high', risk_score: 80.0, warning_signs: ['Speed test failures', 'Actual capacity lower', 'Data corruption reports'], suspicious_reviews: ['Shows 256GB but only holds 32GB', 'All my photos corrupted', 'H2testw failed immediately'], ai_analysis: 'Definite counterfeit. Capacity spoofing is classic indicator.', status: 'flagged', action_taken: 'Marketplace removal requested' },
      { product_name: 'Baby Formula Organic', seller_name: 'BabyNutrition_Plus', platform: 'amazon', review_count: 34, risk_level: 'critical', risk_score: 95.0, warning_signs: ['Lot numbers not in manufacturer database', 'Powder texture different', 'Near expiration dates'], suspicious_reviews: ['Baby rejected it immediately', 'Color is wrong', 'Clumps differently than usual'], ai_analysis: 'CRITICAL RISK. Infant health at stake. Immediate action required.', status: 'escalated', action_taken: 'Emergency report filed with FDA and Amazon' },
      { product_name: 'Premium Headphones Studio', seller_name: 'AudioDealsHQ', platform: 'ebay', review_count: 89, risk_level: 'medium', risk_score: 58.0, warning_signs: ['Serial numbers questionable', 'Build quality inconsistent', 'No warranty registration'], suspicious_reviews: ['Sound is tinny compared to store demo', 'Headband cracked in 2 months', 'Padding is cheaper material'], ai_analysis: 'Possible counterfeit or factory reject. Quality clearly below retail standard.', status: 'monitoring', action_taken: null },
      { product_name: 'Electric Toothbrush Pro', seller_name: 'OralCareExperts', platform: 'amazon', review_count: 267, risk_level: 'low', risk_score: 18.0, warning_signs: [], suspicious_reviews: [], ai_analysis: 'Authorized seller with verified brand relationship. No counterfeit indicators.', status: 'verified', action_taken: 'Verified authentic' }
    ];

    for (const cd of counterfeitDetections) {
      await pool.query(`
        INSERT INTO counterfeit_detections (product_name, seller_name, platform, review_count, risk_level, risk_score, warning_signs, suspicious_reviews, ai_analysis, status, action_taken)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
      `, [cd.product_name, cd.seller_name, cd.platform, cd.review_count, cd.risk_level, cd.risk_score, cd.warning_signs, cd.suspicious_reviews, cd.ai_analysis, cd.status, cd.action_taken]);
    }
    console.log(`${counterfeitDetections.length} counterfeit detections created`);

    // 5. Competitor Monitors (15+ items)
    const competitorMonitors = [
      { competitor_name: 'Pizza Palace', competitor_platform: 'google', business_category: 'Pizza Restaurant', total_reviews: 1234, average_rating: 4.2, sentiment_score: 72.0, strengths: ['Fast delivery', 'Large portions', 'Late night hours'], weaknesses: ['Greasy pizza', 'Limited toppings', 'Cold delivery'], key_differentiators: ['24-hour service', 'Budget pricing'], ai_competitive_analysis: 'Strong on convenience, weak on quality. Opportunity to capture quality-focused customers.', monitoring_status: 'active' },
      { competitor_name: 'Sushi Master', competitor_platform: 'yelp', business_category: 'Japanese Restaurant', total_reviews: 567, average_rating: 4.6, sentiment_score: 85.0, strengths: ['Fresh fish', 'Skilled chefs', 'Authentic experience'], weaknesses: ['High prices', 'Limited seating', 'Long waits'], key_differentiators: ['Omakase experience', 'Fish flown from Japan'], ai_competitive_analysis: 'Premium positioning working well. Hard to compete on quality, consider value positioning.', monitoring_status: 'active' },
      { competitor_name: 'Burger Barn', competitor_platform: 'google', business_category: 'American Restaurant', total_reviews: 2345, average_rating: 3.8, sentiment_score: 58.0, strengths: ['Low prices', 'Quick service', 'Kid-friendly'], weaknesses: ['Quality inconsistent', 'Dirty dining room', 'Rude staff'], key_differentiators: ['Drive-through', 'Value menu'], ai_competitive_analysis: 'Struggling with quality and service. Opportunity to win their dissatisfied customers.', monitoring_status: 'active' },
      { competitor_name: 'Cafe Elegance', competitor_platform: 'yelp', business_category: 'Coffee Shop', total_reviews: 890, average_rating: 4.4, sentiment_score: 78.0, strengths: ['Ambiance', 'Specialty drinks', 'WiFi'], weaknesses: ['Slow service', 'Expensive', 'Limited food'], key_differentiators: ['Instagrammable interior', 'Unique latte art'], ai_competitive_analysis: 'Strong brand image but service issues. Match ambiance while providing better service.', monitoring_status: 'active' },
      { competitor_name: 'Taco Town', competitor_platform: 'google', business_category: 'Mexican Restaurant', total_reviews: 1567, average_rating: 4.0, sentiment_score: 65.0, strengths: ['Authentic recipes', 'Fresh ingredients', 'Family atmosphere'], weaknesses: ['Slow kitchen', 'Parking issues', 'Cash only'], key_differentiators: ['Family-owned since 1985', 'Homemade tortillas'], ai_competitive_analysis: 'Strong on authenticity but operational issues. Can compete with better operations.', monitoring_status: 'active' },
      { competitor_name: 'Noodle House', competitor_platform: 'yelp', business_category: 'Asian Restaurant', total_reviews: 456, average_rating: 4.3, sentiment_score: 75.0, strengths: ['Variety', 'Generous portions', 'Good prices'], weaknesses: ['MSG concerns', 'Basic decor', 'Noisy'], key_differentiators: ['50+ noodle options', 'Build your own bowl'], ai_competitive_analysis: 'Good value proposition. Differentiate with premium ingredients and atmosphere.', monitoring_status: 'active' },
      { competitor_name: 'Steak & Co', competitor_platform: 'google', business_category: 'Steakhouse', total_reviews: 789, average_rating: 4.5, sentiment_score: 82.0, strengths: ['Prime cuts', 'Wine selection', 'Service'], weaknesses: ['Very expensive', 'Formal dress code', 'Need reservations'], key_differentiators: ['Dry-aged beef', 'Sommelier on staff'], ai_competitive_analysis: 'Top-tier competitor. Consider casual upscale positioning to capture different segment.', monitoring_status: 'active' },
      { competitor_name: 'Bakery Bliss', competitor_platform: 'yelp', business_category: 'Bakery', total_reviews: 1234, average_rating: 4.7, sentiment_score: 88.0, strengths: ['Amazing pastries', 'Custom cakes', 'Fresh daily'], weaknesses: ['Sells out early', 'Small space', 'No seating'], key_differentiators: ['French-trained pastry chef', 'Wedding specialist'], ai_competitive_analysis: 'Strong competitor in baked goods. Focus on categories they dont serve well.', monitoring_status: 'active' },
      { competitor_name: 'Quick Bites Deli', competitor_platform: 'google', business_category: 'Deli', total_reviews: 345, average_rating: 3.9, sentiment_score: 62.0, strengths: ['Fast service', 'Cheap', 'Convenient location'], weaknesses: ['Bland food', 'Small portions', 'Cash only'], key_differentiators: ['5-minute lunch guarantee'], ai_competitive_analysis: 'Competing on speed only. Easy to beat on quality while maintaining reasonable speed.', monitoring_status: 'paused' },
      { competitor_name: 'Seafood Shack', competitor_platform: 'yelp', business_category: 'Seafood Restaurant', total_reviews: 678, average_rating: 4.1, sentiment_score: 70.0, strengths: ['Fresh catches', 'Waterfront location', 'Happy hour'], weaknesses: ['Tourist trap vibe', 'Overpriced', 'Wait times'], key_differentiators: ['Dock-to-table', 'Sunset views'], ai_competitive_analysis: 'Location is main advantage. Compete on authenticity and local loyalty.', monitoring_status: 'active' },
      { competitor_name: 'Vegan Vibes', competitor_platform: 'google', business_category: 'Vegetarian Restaurant', total_reviews: 234, average_rating: 4.4, sentiment_score: 80.0, strengths: ['Creative menu', 'Healthy options', 'Eco-friendly'], weaknesses: ['Small portions', 'Expensive', 'Limited hours'], key_differentiators: ['Zero-waste kitchen', 'Local organic sourcing'], ai_competitive_analysis: 'Niche but passionate customer base. Potential partnership opportunity.', monitoring_status: 'active' },
      { competitor_name: 'BBQ Brothers', competitor_platform: 'yelp', business_category: 'BBQ Restaurant', total_reviews: 1890, average_rating: 4.3, sentiment_score: 76.0, strengths: ['Smoky flavor', 'Good sides', 'Beer selection'], weaknesses: ['Inconsistent quality', 'Messy eating', 'Runs out of popular items'], key_differentiators: ['Competition winners', 'House-made sauces'], ai_competitive_analysis: 'Direct competitor with similar positioning. Consistency is their weakness to exploit.', monitoring_status: 'active' },
      { competitor_name: 'Morning Glory Cafe', competitor_platform: 'google', business_category: 'Breakfast Restaurant', total_reviews: 567, average_rating: 4.2, sentiment_score: 73.0, strengths: ['Great coffee', 'Cozy atmosphere', 'Friendly staff'], weaknesses: ['Long weekend waits', 'Limited menu', 'No reservations'], key_differentiators: ['Famous cinnamon rolls', 'Dog-friendly patio'], ai_competitive_analysis: 'Strong breakfast competitor. Differentiate with brunch cocktails and expanded menu.', monitoring_status: 'active' },
      { competitor_name: 'Curry Kingdom', competitor_platform: 'yelp', business_category: 'Indian Restaurant', total_reviews: 445, average_rating: 4.0, sentiment_score: 68.0, strengths: ['Authentic spices', 'Lunch buffet value', 'Vegetarian options'], weaknesses: ['Slow dinner service', 'Dated decor', 'Spice levels inconsistent'], key_differentiators: ['Tandoor oven', 'Regional specialties'], ai_competitive_analysis: 'Solid competitor with loyal following. Modern atmosphere could win younger demographic.', monitoring_status: 'active' },
      { competitor_name: 'French Bistro Lyon', competitor_platform: 'google', business_category: 'French Restaurant', total_reviews: 234, average_rating: 4.6, sentiment_score: 84.0, strengths: ['Authentic French cuisine', 'Romantic setting', 'Expert wine pairing'], weaknesses: ['Very expensive', 'Pretentious vibe', 'Tiny portions'], key_differentiators: ['Chef from Michelin restaurant', 'Seasonal tasting menus'], ai_competitive_analysis: 'High-end competitor. Consider French-inspired casual concept to capture broader market.', monitoring_status: 'active' },
      { competitor_name: 'Thai Treasure', competitor_platform: 'yelp', business_category: 'Thai Restaurant', total_reviews: 567, average_rating: 4.3, sentiment_score: 77.0, strengths: ['Authentic flavors', 'Spice customization', 'Good portions'], weaknesses: ['Slow service', 'Basic presentation', 'Limited parking'], key_differentiators: ['Family recipes', 'Regional Thai dishes'], ai_competitive_analysis: 'Strong on food, weak on experience. Opportunity in elevated Thai dining concept.', monitoring_status: 'active' }
    ];

    for (const cm of competitorMonitors) {
      await pool.query(`
        INSERT INTO competitor_monitors (competitor_name, competitor_platform, business_category, total_reviews, average_rating, sentiment_score, strengths, weaknesses, key_differentiators, ai_competitive_analysis, monitoring_status)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
      `, [cm.competitor_name, cm.competitor_platform, cm.business_category, cm.total_reviews, cm.average_rating, cm.sentiment_score, cm.strengths, cm.weaknesses, cm.key_differentiators, cm.ai_competitive_analysis, cm.monitoring_status]);
    }
    console.log(`${competitorMonitors.length} competitor monitors created`);

    // 6. Personalized Responses (15+ items)
    const personalizedResponses = [
      { reviewer_name: 'Sarah Johnson', reviewer_profile: { loyalty_status: 'VIP', visits: 25, preferred_cuisine: 'Italian', birthday_month: 'March', dietary: 'gluten-free' }, original_review: 'Always love coming here! The gluten-free pasta options are amazing.', review_sentiment: 'positive', personalization_factors: ['VIP status', 'Dietary preferences', 'Repeat customer'], generated_response: 'Dear Sarah, thank you for being such a valued VIP guest! We\'re thrilled our gluten-free pasta continues to delight you. Your 25 visits mean the world to us. See you soon!', tone: 'grateful', personalization_score: 95.0, ai_reasoning: 'High personalization due to VIP status and specific dietary acknowledgment.', status: 'approved' },
      { reviewer_name: 'Mike Chen', reviewer_profile: { loyalty_status: 'new', visits: 1, preferred_cuisine: 'unknown', source: 'Instagram' }, original_review: 'First time here and it was amazing! The ambiance is so Instagrammable!', review_sentiment: 'positive', personalization_factors: ['First-time visitor', 'Social media referral'], generated_response: 'Welcome to our family, Mike! We\'re so glad your first visit exceeded expectations. We\'d love to see your photos - tag us @restaurant! Hope to see you again soon.', tone: 'friendly', personalization_score: 78.0, ai_reasoning: 'Acknowledged first visit and Instagram connection to encourage social sharing.', status: 'approved' },
      { reviewer_name: 'Robert Williams', reviewer_profile: { loyalty_status: 'regular', visits: 12, preferred_items: ['ribeye', 'cabernet'], last_visit: '2024-01-15' }, original_review: 'The ribeye was not up to usual standards this time. Disappointed.', review_sentiment: 'negative', personalization_factors: ['Regular customer', 'Known preferences', 'Quality deviation'], generated_response: 'Robert, we sincerely apologize. As someone who\'s enjoyed our ribeye 12 times, you know our standards - and we fell short. I\'d like to personally ensure your next ribeye and Cabernet are on us. Please reach out directly.', tone: 'apologetic', personalization_score: 92.0, ai_reasoning: 'Deep personalization acknowledging history and offering specific makeup.', status: 'pending' },
      { reviewer_name: 'Emily Davis', reviewer_profile: { loyalty_status: 'regular', visits: 8, family: true, kids_ages: [5, 8] }, original_review: 'Great family dinner! Kids loved the mac and cheese.', review_sentiment: 'positive', personalization_factors: ['Family customer', 'Kids preferences'], generated_response: 'Thank you Emily! We love seeing your family here. Glad the little ones enjoyed the mac and cheese - our chef puts extra love into it! See you all soon.', tone: 'friendly', personalization_score: 85.0, ai_reasoning: 'Family-focused response acknowledging kids and warmth.', status: 'approved' },
      { reviewer_name: 'James Wilson', reviewer_profile: { loyalty_status: 'VIP', visits: 30, account_manager: 'Tom', corporate_account: true }, original_review: 'Perfect for client dinners. Private room was excellent.', review_sentiment: 'positive', personalization_factors: ['Corporate VIP', 'Private event usage', 'Account relationship'], generated_response: 'James, Tom shared your feedback with me personally. We\'re honored to be your choice for client entertainment. Your next private room booking will include complimentary wine service. Thank you for your continued partnership.', tone: 'professional', personalization_score: 98.0, ai_reasoning: 'Maximum personalization with account manager mention and corporate benefit.', status: 'approved' },
      { reviewer_name: 'Lisa Martinez', reviewer_profile: { loyalty_status: 'lapsed', visits: 5, last_visit: '2023-06-15', previous_complaint: 'service speed' }, original_review: 'Gave it another try after a year. Service has improved!', review_sentiment: 'positive', personalization_factors: ['Win-back customer', 'Previous complaint addressed'], generated_response: 'Lisa, welcome back! We took your feedback from last year seriously and made real changes. So happy you noticed the improvement. We\'ve missed you and hope to see you more often.', tone: 'grateful', personalization_score: 90.0, ai_reasoning: 'Acknowledged previous complaint and improvement without being defensive.', status: 'approved' },
      { reviewer_name: 'David Brown', reviewer_profile: { loyalty_status: 'new', visits: 2, referred_by: 'John Smith VIP' }, original_review: 'John was right - this place is fantastic!', review_sentiment: 'positive', personalization_factors: ['Referral customer', 'VIP connection'], generated_response: 'David, any friend of John\'s is a friend of ours! So glad his recommendation led you to us. We\'ll make sure to thank John too. Welcome to the family!', tone: 'friendly', personalization_score: 88.0, ai_reasoning: 'Leveraged referral relationship to build connection.', status: 'approved' },
      { reviewer_name: 'Jennifer Taylor', reviewer_profile: { loyalty_status: 'regular', visits: 15, allergies: ['shellfish', 'peanuts'], notes: 'Always requests corner booth' }, original_review: 'Love that they remember my allergies and my favorite booth!', review_sentiment: 'positive', personalization_factors: ['Allergy awareness', 'Seating preference', 'Attention to detail'], generated_response: 'Jennifer, your safety and comfort are our top priorities. Corner booth 7 will always be waiting for you! Thank you for trusting us with your dining experience for 15 visits.', tone: 'professional', personalization_score: 94.0, ai_reasoning: 'Specific booth mention and allergy acknowledgment shows deep personalization.', status: 'approved' },
      { reviewer_name: 'Thomas Anderson', reviewer_profile: { loyalty_status: 'regular', visits: 10, wine_club_member: true, wine_preference: 'Burgundy' }, original_review: 'The new Burgundy selection is exceptional!', review_sentiment: 'positive', personalization_factors: ['Wine club member', 'Wine expertise', 'Specific preference'], generated_response: 'Thomas, your Burgundy expertise is always appreciated! As a wine club member, we\'d love your thoughts at our next tasting event. I\'ll have our sommelier reach out with exclusive access.', tone: 'professional', personalization_score: 91.0, ai_reasoning: 'Wine club membership and expertise leveraged for exclusive offer.', status: 'pending' },
      { reviewer_name: 'Amanda White', reviewer_profile: { loyalty_status: 'new', visits: 1, occasion: 'anniversary', party_size: 2 }, original_review: 'Perfect anniversary dinner! The special touches made it memorable.', review_sentiment: 'positive', personalization_factors: ['Special occasion', 'Romantic context'], generated_response: 'Congratulations on your anniversary, Amanda! We were honored to be part of your celebration. We\'ve noted your anniversary date - hope to help you celebrate many more!', tone: 'grateful', personalization_score: 86.0, ai_reasoning: 'Anniversary acknowledgment with future celebration hint.', status: 'approved' },
      { reviewer_name: 'Chris Garcia', reviewer_profile: { loyalty_status: 'regular', visits: 18, orders_delivery: true, usual_order: 'Margherita pizza, Caesar salad' }, original_review: 'Delivery was late and pizza was cold.', review_sentiment: 'negative', personalization_factors: ['Delivery customer', 'Regular order known', 'Service failure'], generated_response: 'Chris, I\'m truly sorry. After 18 orders, you deserve better. Your usual Margherita and Caesar should always arrive hot. Next delivery is on us, and I\'m personally reviewing our delivery process.', tone: 'apologetic', personalization_score: 93.0, ai_reasoning: 'Order history knowledge used to show genuine understanding of the failure.', status: 'pending' },
      { reviewer_name: 'Michelle Lee', reviewer_profile: { loyalty_status: 'VIP', visits: 40, preferred_server: 'Maria', usual_table: 'Patio 3' }, original_review: 'Maria always makes our visits special. Best server in town!', review_sentiment: 'positive', personalization_factors: ['Server recognition', 'VIP status', 'Location preference'], generated_response: 'Michelle, we\'ll make sure Maria sees this! Your 40 visits at Patio 3 with Maria are cherished memories for our team too. See you at your usual spot soon!', tone: 'friendly', personalization_score: 97.0, ai_reasoning: 'Maximum personalization with server name, visit count, and table.', status: 'approved' },
      { reviewer_name: 'Kevin Moore', reviewer_profile: { loyalty_status: 'regular', visits: 7, dietary: 'vegan', sustainability_focused: true }, original_review: 'Appreciate the sustainable packaging on takeout orders!', review_sentiment: 'positive', personalization_factors: ['Values alignment', 'Eco-conscious', 'Vegan'], generated_response: 'Kevin, sustainability matters to us too! We\'ve invested in compostable packaging because customers like you inspire us. Our new seasonal vegan menu launches next month - hope you\'ll try it!', tone: 'friendly', personalization_score: 89.0, ai_reasoning: 'Values alignment with eco and vegan messaging.', status: 'approved' },
      { reviewer_name: 'Patricia Robinson', reviewer_profile: { loyalty_status: 'new', visits: 1, source: 'birthday gift card', first_impression: 'important' }, original_review: 'Used my birthday gift card. Food was good but nothing special.', review_sentiment: 'neutral', personalization_factors: ['Gift card recipient', 'First impression opportunity', 'Birthday context'], generated_response: 'Happy belated birthday, Patricia! We\'d love a chance to truly wow you. Please reach out - I\'d like to personally arrange your next visit to show you what makes us special.', tone: 'friendly', personalization_score: 82.0, ai_reasoning: 'Birthday acknowledgment with invitation to give second chance.', status: 'draft' },
      { reviewer_name: 'Daniel Jackson', reviewer_profile: { loyalty_status: 'lapsed', visits: 20, last_visit: '2022-12-01', reason_lapsed: 'moved away', returned: true }, original_review: 'Moved back to town and this was my first stop. Still the best!', review_sentiment: 'positive', personalization_factors: ['Returned customer', 'Long history', 'Emotional connection'], generated_response: 'Daniel, welcome home! We wondered where our 20-visit regular went. So happy the move brought you back to us. Your old favorite is waiting - first one\'s on the house to celebrate your return!', tone: 'grateful', personalization_score: 95.0, ai_reasoning: 'Emotional homecoming response with history acknowledgment.', status: 'approved' },
      { reviewer_name: 'Nancy Thompson', reviewer_profile: { loyalty_status: 'VIP', visits: 35, complaint_history: ['2023-03 noise', '2023-08 AC'], special_requests: 'quiet table' }, original_review: 'Finally got a quiet table away from the bar. Thank you for listening!', review_sentiment: 'positive', personalization_factors: ['Complaint resolution', 'Long-term patience', 'Accommodation success'], generated_response: 'Nancy, your patience means everything. After 35 visits, you deserve perfection. We\'ve noted your quiet table preference permanently. Thank you for giving us the chance to get it right.', tone: 'grateful', personalization_score: 94.0, ai_reasoning: 'Complaint history acknowledged with permanent solution.', status: 'approved' }
    ];

    for (const pr of personalizedResponses) {
      await pool.query(`
        INSERT INTO personalized_responses (reviewer_name, reviewer_profile, original_review, review_sentiment, personalization_factors, generated_response, tone, personalization_score, ai_reasoning, status)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
      `, [pr.reviewer_name, pr.reviewer_profile, pr.original_review, pr.review_sentiment, pr.personalization_factors, pr.generated_response, pr.tone, pr.personalization_score, pr.ai_reasoning, pr.status]);
    }
    console.log(`${personalizedResponses.length} personalized responses created`);

    // 7. Review Solicitations (15+ items)
    const reviewSolicitations = [
      { customer_name: 'John Smith', customer_email: 'john.smith@email.com', customer_phone: '555-0101', purchase_date: '2024-12-15', product_service: 'Dinner for 4', optimal_send_time: '2024-12-18 10:00:00', channel: 'email', message_template: 'Hi {name}, thank you for dining with us! We\'d love to hear about your experience.', personalized_message: 'Hi John, thank you for celebrating with us last Sunday! Your party of 4 seemed to really enjoy the tasting menu. We\'d love to hear your thoughts - your feedback helps us serve you better.', ai_timing_reason: '3 days post-visit, morning send for professional audience', status: 'sent', sent_at: '2024-12-18 10:00:00', response_received: true },
      { customer_name: 'Mary Johnson', customer_email: 'mary.j@email.com', customer_phone: '555-0102', purchase_date: '2024-12-20', product_service: 'Birthday Celebration', optimal_send_time: '2024-12-23 14:00:00', channel: 'email', message_template: 'Hi {name}, hope you had a wonderful celebration!', personalized_message: 'Hi Mary, we hope your birthday celebration was everything you dreamed of! The team loved making your day special. Would you share your experience with others?', ai_timing_reason: '3 days post-event, afternoon for personal occasions', status: 'sent', sent_at: '2024-12-23 14:00:00', response_received: false },
      { customer_name: 'Robert Davis', customer_email: 'rdavis@company.com', customer_phone: '555-0103', purchase_date: '2024-12-22', product_service: 'Business Lunch', optimal_send_time: '2024-12-24 09:00:00', channel: 'email', message_template: 'Hi {name}, thank you for choosing us for your business meeting.', personalized_message: 'Hi Robert, thank you for hosting your business lunch with us on Friday. We hope the private room provided the perfect setting for your meeting. Your professional review would mean a lot.', ai_timing_reason: '2 days for business customers, early morning', status: 'scheduled', sent_at: null, response_received: false },
      { customer_name: 'Susan Wilson', customer_email: 'susan.w@email.com', customer_phone: '555-0104', purchase_date: '2024-12-21', product_service: 'Takeout Order', optimal_send_time: '2024-12-22 18:00:00', channel: 'sms', message_template: 'Thanks for your order! How was it?', personalized_message: 'Hi Susan! Hope you enjoyed last night\'s takeout. Our pad thai traveled well? Quick review would help others discover us! [link]', ai_timing_reason: 'Next day evening for takeout, SMS for quick feedback', status: 'sent', sent_at: '2024-12-22 18:00:00', response_received: true },
      { customer_name: 'Michael Brown', customer_email: 'mbrown@email.com', customer_phone: '555-0105', purchase_date: '2024-12-19', product_service: 'Wine Tasting Event', optimal_send_time: '2024-12-22 11:00:00', channel: 'email', message_template: 'Hi {name}, we hope you enjoyed the wine tasting!', personalized_message: 'Hi Michael, our sommelier mentioned you had some great questions during Thursday\'s tasting! Would you share your experience? Your wine expertise would make for a valuable review.', ai_timing_reason: '3 days post-event, mid-morning for wine enthusiasts', status: 'sent', sent_at: '2024-12-22 11:00:00', response_received: true },
      { customer_name: 'Jennifer Taylor', customer_email: 'jtaylor@email.com', customer_phone: '555-0106', purchase_date: '2024-12-23', product_service: 'Brunch', optimal_send_time: '2024-12-25 10:00:00', channel: 'email', message_template: 'Hi {name}, thanks for brunching with us!', personalized_message: 'Hi Jennifer, we loved having you for Saturday brunch! How were the mimosas and eggs benedict? A review would be the perfect holiday gift for our team!', ai_timing_reason: '2 days post-brunch, morning timing matches meal type', status: 'scheduled', sent_at: null, response_received: false },
      { customer_name: 'David Anderson', customer_email: 'david.a@email.com', customer_phone: '555-0107', purchase_date: '2024-12-18', product_service: 'Anniversary Dinner', optimal_send_time: '2024-12-21 15:00:00', channel: 'email', message_template: 'Hi {name}, congratulations again on your anniversary!', personalized_message: 'Hi David, congratulations again on 10 years! We were honored to be part of your celebration. Your love story deserves to be shared - would you tell others about your experience?', ai_timing_reason: '3 days post-special occasion, afternoon for couples', status: 'sent', sent_at: '2024-12-21 15:00:00', response_received: true },
      { customer_name: 'Lisa Martinez', customer_email: 'lisa.m@email.com', customer_phone: '555-0108', purchase_date: '2024-12-24', product_service: 'Christmas Eve Dinner', optimal_send_time: '2024-12-27 12:00:00', channel: 'email', message_template: 'Hi {name}, we hope you had a magical Christmas Eve!', personalized_message: 'Hi Lisa, we hope your family Christmas Eve dinner was magical! The kids seemed to love the special holiday menu. Would you share your holiday experience with others?', ai_timing_reason: '3 days post-holiday, noon for families', status: 'scheduled', sent_at: null, response_received: false },
      { customer_name: 'James Wilson', customer_email: 'jwilson@email.com', customer_phone: '555-0109', purchase_date: '2024-12-17', product_service: 'Catering Order', optimal_send_time: '2024-12-19 10:00:00', channel: 'email', message_template: 'Hi {name}, how did the catering go?', personalized_message: 'Hi James, we hope your office holiday party was a hit! Our team put extra love into your catering order for 50. How did your colleagues enjoy it? A review would help other event planners find us.', ai_timing_reason: '2 days for catering, morning for business contacts', status: 'sent', sent_at: '2024-12-19 10:00:00', response_received: true },
      { customer_name: 'Patricia Garcia', customer_email: 'pgarcia@email.com', customer_phone: '555-0110', purchase_date: '2024-12-20', product_service: 'Date Night', optimal_send_time: '2024-12-23 19:00:00', channel: 'sms', message_template: 'Hope date night was special!', personalized_message: 'Hi Patricia! Hope Friday\'s date night was special. The chef\'s tasting menu is made for romance. Quick review? [link]', ai_timing_reason: 'Evening SMS matches romantic dining context', status: 'sent', sent_at: '2024-12-23 19:00:00', response_received: false },
      { customer_name: 'Christopher Lee', customer_email: 'clee@email.com', customer_phone: '555-0111', purchase_date: '2024-12-22', product_service: 'Cooking Class', optimal_send_time: '2024-12-25 16:00:00', channel: 'email', message_template: 'Hi {name}, hope you\'re cooking up a storm!', personalized_message: 'Hi Christopher, have you tried making the risotto at home yet? Our chef loved your enthusiasm in Saturday\'s class! Would you share your experience? It helps aspiring home chefs discover us.', ai_timing_reason: '3 days post-class, afternoon for hobby activities', status: 'scheduled', sent_at: null, response_received: false },
      { customer_name: 'Sarah Thompson', customer_email: 'sthompson@email.com', customer_phone: '555-0112', purchase_date: '2024-12-16', product_service: 'Gift Card Purchase', optimal_send_time: '2024-12-30 10:00:00', channel: 'email', message_template: 'Hi {name}, hope your gift brought joy!', personalized_message: 'Hi Sarah, the holidays have passed - did your gift recipient enjoy their dining experience? We\'d love to hear about it, and any review of our gift cards helps others choose the perfect present!', ai_timing_reason: 'Post-holiday for gift card follow-up', status: 'scheduled', sent_at: null, response_received: false },
      { customer_name: 'Daniel Moore', customer_email: 'dmoore@email.com', customer_phone: '555-0113', purchase_date: '2024-12-21', product_service: 'Bar Happy Hour', optimal_send_time: '2024-12-23 17:00:00', channel: 'sms', message_template: 'Thanks for happy hour!', personalized_message: 'Hey Daniel! Thanks for kicking off the weekend at our bar. Those craft cocktails hit different. Drop us a review? [link]', ai_timing_reason: 'Happy hour timing, SMS for casual bar customers', status: 'sent', sent_at: '2024-12-23 17:00:00', response_received: false },
      { customer_name: 'Michelle White', customer_email: 'mwhite@email.com', customer_phone: '555-0114', purchase_date: '2024-12-19', product_service: 'Private Dining Room', optimal_send_time: '2024-12-22 11:00:00', channel: 'email', message_template: 'Hi {name}, thank you for booking our private room!', personalized_message: 'Hi Michelle, thank you for choosing our private dining room for your team celebration! Hosting your group of 20 was our pleasure. A review would help other event coordinators discover our private dining options.', ai_timing_reason: '3 days post-event, mid-morning for professionals', status: 'sent', sent_at: '2024-12-22 11:00:00', response_received: true },
      { customer_name: 'Kevin Robinson', customer_email: 'krobinson@email.com', customer_phone: '555-0115', purchase_date: '2024-12-23', product_service: 'First Visit', optimal_send_time: '2024-12-26 14:00:00', channel: 'email', message_template: 'Hi {name}, thank you for choosing us!', personalized_message: 'Hi Kevin, thank you for giving us a try on Saturday! First impressions matter, and we hope we made a great one. Would you share your experience? New customer reviews are incredibly valuable to us.', ai_timing_reason: '3 days post first visit, afternoon for thoughtful response', status: 'scheduled', sent_at: null, response_received: false },
      { customer_name: 'Amanda Jackson', customer_email: 'ajackson@email.com', customer_phone: '555-0116', purchase_date: '2024-12-20', product_service: 'Loyalty Milestone - 10th Visit', optimal_send_time: '2024-12-23 10:00:00', channel: 'email', message_template: 'Hi {name}, thank you for being such a loyal guest!', personalized_message: 'Hi Amanda, wow - your 10th visit! You\'re officially part of the family. We\'d be honored if you shared what keeps bringing you back. Your perspective as a regular would be so valuable to others.', ai_timing_reason: 'Milestone celebration timing, morning for positive mood', status: 'sent', sent_at: '2024-12-23 10:00:00', response_received: true }
    ];

    for (const rs of reviewSolicitations) {
      await pool.query(`
        INSERT INTO review_solicitations (customer_name, customer_email, customer_phone, purchase_date, product_service, optimal_send_time, channel, message_template, personalized_message, ai_timing_reason, status, sent_at, response_received)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
      `, [rs.customer_name, rs.customer_email, rs.customer_phone, rs.purchase_date, rs.product_service, rs.optimal_send_time, rs.channel, rs.message_template, rs.personalized_message, rs.ai_timing_reason, rs.status, rs.sent_at, rs.response_received]);
    }
    console.log(`${reviewSolicitations.length} review solicitations created`);

    console.log('\n===========================================');
    console.log('Database seeded successfully!');
    console.log('===========================================');
    console.log('\nDemo Login Credentials:');
    console.log('Email: admin@reviewmanager.com');
    console.log('Password: admin123');
    console.log('===========================================\n');

    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
};

seedDatabase();
